steps:
  # Step 1: Checkout the source code from the repository.
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--depth=1', '--recursive', 'https://github.com/IT30/terraform.git']

  # Step 2: Set up the Terraform environment.
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        apk add --no-cache curl
        curl -fsSL https://releases.hashicorp.com/terraform/1.0.3/terraform_1.0.3_linux_amd64.zip -o terraform.zip
        unzip terraform.zip
        rm terraform.zip
        chmod +x terraform
        mv terraform /usr/local/bin/
        
  
        
  # Step 4: Apply Terraform configuration.
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args:
      - 'apply'
      - '-auto-approve'
